# Generated by Django 5.2 on 2025-05-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
