# Generated by Django 5.2 on 2025-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("paystack", "Paystack")], max_length=50
            ),
        ),
    ]
